site_name: Constellation Developer

theme:
  name: material
  features:
    - content.code.copy
    - content.tooltips
nav:
  - Homepage: index.md
  - Contributing: contributing.md
  - Tungsten:
      - Introduction: tungsten/introduction.md
      - Scan&Shop: tungsten/scanshop.md
markdown_extensions:
  - admonition
  - attr_list