name: deploy

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  
    
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' 

      - name: install mkdocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          pip install mkdocs

      - name: build site
        run: mkdocs build --clean 

      - name: deploy to gh pages
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add -f site
          git commit -m "Deploy"
          git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" HEAD:gh-pages
